{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shop-console.fullname" . }}-grafana-provisioning
  labels:
    app.kubernetes.io/name: {{ include "shop-console.name" . }}
    app.kubernetes.io/component: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  datasources.yml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{ include "shop-console.fullname" . }}-prometheus:{{ .Values.monitoring.prometheus.service.port }}
        isDefault: true
        editable: false
{{- end }}

