apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shop-console.fullname" . }}-secrets
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo.rootUsername | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongo.rootPassword | quote }}

  MONGO_URL: {{ include "shop-console.mongoUrl" . | quote }}
  MONGO_DB_NAME: {{ .Values.mongo.dbName | quote }}

  POSTGRES_HOST: {{ include "shop-console.postgresServiceName" . | quote }}
  POSTGRES_PORT: "5432"
  POSTGRES_DB: {{ .Values.postgres.dbName | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}

  AUTH_REALM: {{ .Release.Namespace | quote }}
  AUTH_ADMIN_USERNAME: {{ .Values.auth.admin.username | quote }}
  AUTH_ADMIN_PASSWORD: {{ .Values.auth.admin.password | quote }}
  AUTH_MANAGER_USERNAME: {{ .Values.auth.manager.username | quote }}
  AUTH_MANAGER_PASSWORD: {{ .Values.auth.manager.password | quote }}
  AUTH_USER_USERNAME: {{ .Values.auth.user.username | quote }}
  AUTH_USER_PASSWORD: {{ .Values.auth.user.password | quote }}
  AUTH_GUEST_USERNAME: {{ .Values.auth.guest.username | quote }}
  AUTH_GUEST_PASSWORD: {{ .Values.auth.guest.password | quote }}

