apiVersion: v1
kind: Service
metadata:
  name: {{ include "shop-console.mongoServiceName" . }}
  labels:
    {{- include "shop-console.mongoLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  selector:
    {{- include "shop-console.mongoLabels" . | nindent 4 }}

