apiVersion: v1
kind: Service
metadata:
  name: {{ include "shop-console.fullname" . }}-api
  labels:
    {{- include "shop-console.apiLabels" . | nindent 4 }}
spec:
  type: {{ .Values.exposure.api.type }}
  selector:
    {{- include "shop-console.apiLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      {{- if and (eq .Values.exposure.api.type "NodePort") .Values.exposure.api.nodePort }}
      nodePort: {{ .Values.exposure.api.nodePort }}
      {{- end }}
